### PR TITLE
made progress on study spaces page with populating from backend data

### PR DESCRIPTION
**Pull request by bhillyard**
connected first study space page with button on homepage and made study sessions populated from database that are clickable to a new page that populates with data from that specific study space

### CODE REVIEW

**Comment by Twicee** [comment]
Looks great Brett! Nice job

**Review by Twicee — APPROVED** [review]
Looks great Brett! Keep up the good work!

**Review by cheungkelly — COMMENTED** [review]
Great Job!

**Comment by JCYaya** [comment]
great work

**Pull request merged**
